version: '2'

services:
  postgres:
    environment:
      - POSTGRES_PASSWORD=jT7I6MZsakUj
    image: davefelce/mysites_postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  logstash:
    image: davefelce/mysites_logstash
    depends_on:
      - elasticsearch
      - postgres
  estateagent:
    environment:
      - DJANGO_LOCAL=0
    image: davefelce/mysites_estateagentdjangodemo_webapp
    ports:
      - "8000:8000"
      - "8081:8081"
    depends_on:
      - elasticsearch
      - postgres
  whatsinmyfridge:
    environment:
      - DJANGO_LOCAL=0
    image: davefelce/mysites_whatsinmyfridge_webapp
    ports:
      - "8001:8001"
      - "8082:8082"
    depends_on:
      - elasticsearch
      - postgres

volumes:
  esdata:
    driver: local
  pgdata:
    driver: local
